# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node: ['16', '14', '12']

    name: Node v${{ matrix.node }}
    steps:
      - name: Checkout Commit
      - uses: actions/checkout@v2

      - name: Checkout Master
        run: git branch -f master origin/master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: install pnpm
        run: npm install pnpm -g

      - name: pnpm install
        run: pnpm install --ignore-scripts

      - name: run tests
        run: pnpm run test
